//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAnswer
    {
        public int Ca_Id { get; set; }
        public Nullable<int> Ca_CandadateRepositoryId { get; set; }
        public Nullable<int> Ca_QustionId { get; set; }
        public Nullable<int> Ca_SelectedOption { get; set; }
    
        public virtual CandidateRepository CandidateRepository { get; set; }
        public virtual QuizzQuestionMaster QuizzQuestionMaster { get; set; }
        public virtual QuizzQustionsOption QuizzQustionsOption { get; set; }
    }
}
