//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMaster
    {
        public CandidateMaster()
        {
            this.CandidateRepositories = new HashSet<CandidateRepository>();
        }
    
        public int Candidate_ID { get; set; }
        public string Candidate_Name { get; set; }
        public string Candidate_EmailId { get; set; }
        public string CandidatePassword { get; set; }
    
        public virtual ICollection<CandidateRepository> CandidateRepositories { get; set; }
    }
}
