//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateRepository
    {
        public CandidateRepository()
        {
            this.CandidateAnswers = new HashSet<CandidateAnswer>();
        }
    
        public int Cq_ID { get; set; }
        public Nullable<int> Cq_CandidateId { get; set; }
        public Nullable<int> Cq_QuizzId { get; set; }
        public Nullable<System.DateTime> Cq_Date { get; set; }
    
        public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; }
        public virtual CandidateMaster CandidateMaster { get; set; }
        public virtual QuizzQustionMaping QuizzQustionMaping { get; set; }
    }
}
