//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizzLevel
    {
        public QuizzLevel()
        {
            this.QuizzMapings = new HashSet<QuizzMaping>();
        }
    
        public int Ql_Id { get; set; }
        public string Ql_Type { get; set; }
    
        public virtual ICollection<QuizzMaping> QuizzMapings { get; set; }
    }
}
