//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizzQustionsOption
    {
        public QuizzQustionsOption()
        {
            this.CandidateAnswers = new HashSet<CandidateAnswer>();
        }
    
        public int Qo_Id { get; set; }
        public string Qo_AnswerText { get; set; }
    
        public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; }
    }
}
