//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Data.Entity.Infrastructure;
    //   using System.Data.Objects;
    // using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QuizzesDbEntities : DbContext
    {
        public QuizzesDbEntities()
            : base("name=QuizzesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CandidateAnswer> CandidateAnswers { get; set; }
        public DbSet<CandidateMaster> CandidateMasters { get; set; }
        public DbSet<CandidateRepository> CandidateRepositories { get; set; }
        public DbSet<QuizzLevel> QuizzLevels { get; set; }
        public DbSet<QuizzMaping> QuizzMapings { get; set; }
        public DbSet<QuizzQuestionMaster> QuizzQuestionMasters { get; set; }
        public DbSet<QuizzQustionMaping> QuizzQustionMapings { get; set; }
        public DbSet<QuizzQustionsOption> QuizzQustionsOptions { get; set; }
        public DbSet<QuizzSubject> QuizzSubjects { get; set; }
    
        [EdmFunction("QuizzesDbEntities", "GetScoreCardForUser")]
        public virtual IQueryable<GetScoreCardForUser_Result> GetScoreCardForUser(Nullable<int> examRepositoryId)
        {
            var examRepositoryIdParameter = examRepositoryId.HasValue ?
                new ObjectParameter("ExamRepositoryId", examRepositoryId) :
                new ObjectParameter("ExamRepositoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetScoreCardForUser_Result>("[QuizzesDbEntities].[GetScoreCardForUser](@ExamRepositoryId)", examRepositoryIdParameter);
        }
    }
}
