//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizzQuestionMaster
    {
        public QuizzQuestionMaster()
        {
            this.CandidateAnswers = new HashSet<CandidateAnswer>();
            this.QuizzQustionMapings = new HashSet<QuizzQustionMaping>();
            this.QuizzQustionMapings1 = new HashSet<QuizzQustionMaping>();
        }
    
        public int Qq_Id { get; set; }
        public Nullable<int> Qq_QuizzId { get; set; }
        public string Qq_Question { get; set; }
    
        public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; }
        public virtual QuizzMaping QuizzMaping { get; set; }
        public virtual ICollection<QuizzQustionMaping> QuizzQustionMapings { get; set; }
        public virtual ICollection<QuizzQustionMaping> QuizzQustionMapings1 { get; set; }
    }
}
